name: Cloud Infrastructure & App Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ vars.GCP_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Bootstrap Backend Bucket
        run: |
          # Check de existencia seguro: Crea el bucket solo si no existe.
          # Esto protege el contenido y el estado de Terraform en entornos existentes.
          if ! gcloud storage buckets describe gs://${{ vars.GCP_PROJECT_ID }}-lake >/dev/null 2>&1; then
            echo "El bucket no existe. Inicializando infraestructura base..."
            gcloud storage buckets create gs://${{ vars.GCP_PROJECT_ID }}-lake \
              --location=${{ vars.GCP_REGION }} \
              --project=${{ vars.GCP_PROJECT_ID }}
          else
            echo "Bucket detectado. Procediendo con el despliegue seguro del estado."
          fi

      - name: Package Function Code
        run: |
          # Empaquetado selectivo: solo producci√≥n, excluyendo benchmarks y notebooks
          zip -r source.zip main.py src/ requirements.txt -x "src/benchmark.py" "src/benchmark_results.txt" "src/challenge.ipynb"
          mv source.zip terraform/source.zip

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init \
            -backend-config="bucket=${{ vars.GCP_PROJECT_ID }}-lake" \
            -backend-config="prefix=terraform"

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
